apiVersion: apps/v1
kind: Deployment
metadata:
  name: wolvox-integration
  namespace: wolvox
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wolvox-integration
  template:
    metadata:
      labels:
        app: wolvox-integration
    spec:
      containers:
      - name: wolvox-integration
        image: wolvox-integration:latest
        ports:
        - containerPort: 8000
        env:
        - name: REDIS_HOST
          value: redis-service
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 30
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi" 