apiVersion: v1
kind: Service
metadata:
  name: wolvox-backend
  labels:
    app: wolvox-backend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: wolvox-backend 